version: "3.9"

services:
  postgres:
    container_name: postgres_db
    restart: always
    build: ./
    environment:
      POSTGRES_DB: "Witcher"
      POSTGRES_USER: "erlendum"
      POSTGRES_PASSWORD: "parasha"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
        - ./data:/var/lib/postgresql/data
