version: "3.9"

services:
  postgres:
    container_name: postgres_db_rk_02
    restart: always
    build: ./
    environment:
      POSTGRES_DB: "RK2"
      POSTGRES_USER: "erlendum"
      POSTGRES_PASSWORD: "parasha"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5431:5432"
